global:
  scrape_interval: 60s
  scrape_timeout: 20s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'napijse:8080'

rule_files:
  - alert.yml