package mk.napijse.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class FullPageTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = getDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  private WebDriver getDriver() {
    System.setProperty("webdriver.chrome.driver", "/Users/goras/chromedriver.exe");
    return new ChromeDriver();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fullPageTest() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(974, 1040));
    driver.findElement(By.linkText("Најава")).click();
    driver.findElement(By.id("username")).sendKeys("gorast.angelovski");
    driver.findElement(By.id("password")).sendKeys("ga");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    {
      WebElement element = driver.findElement(By.id("username"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("user");
    driver.findElement(By.id("password")).sendKeys("user");
    driver.findElement(By.cssSelector(".fourth")).click();
    driver.findElement(By.linkText("Рецепти")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.linkText("3")).click();
    driver.findElement(By.id("recipeName")).click();
    driver.findElement(By.id("recipeName")).sendKeys("smuti");
    driver.findElement(By.cssSelector(".add-recipe:nth-child(5)")).click();
    driver.findElement(By.id("recipeName")).sendKeys("смути");
    driver.findElement(By.cssSelector(".add-recipe:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) form:nth-child(1) > .add-to-cart-btn")).click();
    driver.findElement(By.id("content")).click();
    driver.findElement(By.id("content")).sendKeys("добро смути :)");
    driver.findElement(By.cssSelector(".add-recipe:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".edit-balloon-btn")).click();
    driver.findElement(By.id("content")).click();
    driver.findElement(By.id("content")).click();
    {
      WebElement element = driver.findElement(By.id("content"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("content")).sendKeys("ЛОшо смути :(");
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.cssSelector(".delete-balloon-btn")).click();
    driver.findElement(By.linkText("Рецепти")).click();
    driver.findElement(By.cssSelector(".add-recipe:nth-child(1)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Рецепта");
    driver.findElement(By.id("description")).sendKeys("Сечи, мачкај, јади");
    driver.findElement(By.id("ingredients")).sendKeys("леб, нутела");
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) form:nth-child(2) > .add-to-cart-btn")).click();
    driver.findElement(By.linkText("Мои Рецепти")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) .delete-balloon-btn")).click();
    driver.findElement(By.linkText("Мои Рецепти")).click();
    driver.findElement(By.cssSelector(".column:nth-child(1) .edit-balloon-btn")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2)")).click();
    driver.findElement(By.id("description")).sendKeys("нова рецепта");
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("Омилени")).click();
    driver.findElement(By.cssSelector(".column:nth-child(2) .delete-from-favorites")).click();
    driver.findElement(By.linkText("Одјави се")).click();
    driver.findElement(By.id("username")).sendKeys("gorast.angelovski");
    driver.findElement(By.id("password")).sendKeys("ga");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector(".fourth")).click();
    driver.findElement(By.id("username")).sendKeys("gorast.angelovski");
    driver.findElement(By.id("password")).sendKeys("ga");
    driver.findElement(By.cssSelector(".fourth")).click();
    driver.findElement(By.linkText("Рецепти")).click();
    driver.findElement(By.cssSelector(".column:nth-child(1) form:nth-child(1) > .add-to-cart-btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .delete-balloon-btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .delete-balloon-btn")).click();
    driver.findElement(By.cssSelector(".delete-balloon-btn")).click();
    driver.findElement(By.linkText("ADMIN")).click();
    driver.findElement(By.cssSelector(".row:nth-child(3) .admin-btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .admin-btn")).click();
    driver.findElement(By.cssSelector("div:nth-child(7) .center")).click();
    driver.findElement(By.linkText("Одјави се")).click();
    driver.findElement(By.id("username")).sendKeys("gorast.angelovski");
    driver.findElement(By.id("password")).sendKeys("ga");
  }
}
