name: Lint, Docker Build and Push to DockerHub

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linter:
    name: Lint Code Base - Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Login, build and push to dockerhub
    needs: linter
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Image
        run: docker build . -f ${WORKSPACE}/Dockerfile --tag rilievsk/napijse-devops:latest
      -
        name: Docker Push Image
        run: docker push rilievsk/napijse-devops